# Generated by Django 4.2.12 on 2024-08-10 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'страна',
                'verbose_name_plural': 'Страны',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FilmsdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('verified', models.BooleanField(default=False, help_text='Снимите галочку, если все проверено.', verbose_name='Проверено')),
                ('is_published', models.BooleanField(default=False, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано')),
                ('id_kp', models.IntegerField(unique=True, verbose_name='id кинопоиска')),
                ('name_orig', models.CharField(blank=True, max_length=256, null=True, verbose_name='Оригинальное название')),
                ('year', models.IntegerField(verbose_name='Год')),
                ('poster', models.TextField(blank=True, help_text='Пример: http://оригинал, http://превью', verbose_name='Постер')),
                ('rating', models.FloatField(blank=True, default=0, null=True, verbose_name='Рейтинг')),
                ('votecount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Голосов')),
                ('description', models.TextField(default='Нет описания', null=True, verbose_name='Описание')),
                ('scrinshot', models.TextField(blank=True, help_text='imageUrl - оригинал, "previewUrl - превью[{"imageUrl": "ссылка", "previewUrl": "ссылка"}, ]', null=True, verbose_name='Скриншоты')),
                ('cat', models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.category', verbose_name='Категория')),
                ('country', models.ManyToManyField(blank=True, help_text='Зажмите Ctrl и выберите', to='films.country', verbose_name='Страна')),
                ('genres', models.ManyToManyField(blank=True, help_text='Зажмите Ctrl и выберите', to='films.genres', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ('-created_at',),
                'abstract': False,
                'default_related_name': 'posts',
            },
        ),
    ]
