# Generated by Django 4.2.12 on 2024-08-09 22:37

from django.db import migrations, models
import films.validators


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsdmodel',
            name='id_kp',
            field=models.IntegerField(unique=True, validators=[films.validators.erorr_id_kp], verbose_name='id кинопоиска'),
        ),
    ]
