# Generated by Django 5.0.7 on 2024-08-06 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_rename_id_kp_filmsdmodel_kinopoisk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filmsdmodel',
            old_name='kinopoisk',
            new_name='id_kp',
        ),
    ]
