# Generated by Django 4.2.12 on 2024-08-09 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_filmsdmodel_id_kp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsdmodel',
            name='id_kp',
            field=models.IntegerField(unique=True, verbose_name='id кинопоиска'),
        ),
    ]
