# Generated by Django 5.0.7 on 2024-08-06 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_rename_kinopoisk_filmsdmodel_id_kp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsdmodel',
            name='id_kp',
            field=models.IntegerField(unique=True, verbose_name='id кинопоиска'),
        ),
    ]
