# Generated by Django 5.1.2 on 2024-10-21 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_coment_options_remove_coment_name_coment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsdmodel',
            name='description',
            field=models.TextField(blank=True, default='Нет описания', null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='filmsdmodel',
            name='poster',
            field=models.TextField(blank=True, help_text='Пример: http://оригинал, http://превью', null=True, verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='filmsdmodel',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год'),
        ),
    ]
