volumes:
  static:
  media:
  mysql_data:

services:
  db_mysql:
    image: mysql  # или другая версия, например, mysql:5.7
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root_password  # Задайте пароль для root
      MYSQL_DATABASE: my_database         # Имя базы данных, которую хотите создать
      MYSQL_USER: user                    # Пользователь базы данных
      MYSQL_PASSWORD: user_password       # Пароль пользователя
    volumes:
      - mysql_data:/var/lib/mysql  # Хранение данных в volume
    ports:
      - "3306:3306"                # Проброс порта для доступа к базе данных
  # db:
  #   image: postgres:13
  #   env_file: .env
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    depends_on:
      - db_mysql
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      cp -r /app/static_backend/. /backend_static/ &&
      cp -r /app/static_dev/. /backend_static/ &&
      gunicorn --bind 0.0.0.0:8000 kinoz.wsgi"
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/static
      - media:/media
