# Generated by Django 5.0.6 on 2024-06-22 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FilmsdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию.', verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('name_orig', models.CharField(max_length=256, verbose_name='Оригинальное')),
                ('year', models.IntegerField(max_length=256, verbose_name='Год')),
                ('poster', models.TextField(verbose_name='Постер')),
                ('country', models.TextField(default='Не известно', verbose_name='Страна')),
                ('genres', models.TextField(default='Не известно', verbose_name='Жанр')),
                ('rating', models.FloatField(verbose_name='Рейтинг')),
                ('votecount', models.IntegerField(verbose_name='Голосов')),
                ('description', models.TextField(default='Нет описания', verbose_name='Описание')),
                ('cat', models.CharField(max_length=256, verbose_name='Категория')),
                ('scrinshot', models.TextField(verbose_name='Скриншоты')),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ('created_at',),
            },
        ),
    ]
