# Generated by Django 5.0.6 on 2024-06-22 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsdmodel',
            name='year',
            field=models.IntegerField(verbose_name='Год'),
        ),
    ]
