# Generated by Django 5.0.6 on 2024-06-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_filmsdmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filmsdmodel',
            name='scrinshot',
            field=models.TextField(default=None, verbose_name='Скриншоты'),
        ),
    ]
