# Generated by Django 5.1.4 on 2024-12-27 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coment',
            options={'default_related_name': 'coments', 'ordering': ('-created_at',), 'verbose_name': 'комментарии', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
