# Generated by Django 5.1.4 on 2025-01-06 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('films', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='filmsdmodel',
            name='cat',
            field=models.ForeignKey(blank=True, max_length=256, null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='filmsdmodel',
            name='country',
            field=models.ManyToManyField(blank=True, help_text='Зажмите Ctrl и выберите', to='films.country', verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='favorite',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.filmsdmodel', verbose_name='Фильм'),
        ),
        migrations.AddField(
            model_name='coment',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.filmsdmodel', verbose_name='Фильм'),
        ),
        migrations.AddField(
            model_name='filmsdmodel',
            name='genres',
            field=models.ManyToManyField(blank=True, help_text='Зажмите Ctrl и выберите', to='films.genres', verbose_name='Жанр'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'film'), name='unique_user_film'),
        ),
    ]
