# Generated by Django 5.1.2 on 2024-12-21 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coments', to='films.filmsdmodel', verbose_name='Фильм'),
        ),
        migrations.AlterField(
            model_name='coment',
            name='text',
            field=models.TextField(verbose_name='Текст'),
        ),
    ]
