# Generated by Django 5.1.4 on 2024-12-27 20:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_alter_coment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coment',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.filmsdmodel', verbose_name='Фильм'),
        ),
    ]
