# Generated by Django 5.1.4 on 2025-01-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmsdmodel',
            name='torrent',
            field=models.FileField(blank=True, null=True, upload_to='torrent/', verbose_name='Торрент'),
        ),
    ]
