# Generated by Django 5.1.4 on 2025-01-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filmsdmodel',
            name='actors',
            field=models.TextField(blank=True, null=True, verbose_name='Актеры'),
        ),
    ]
