# Generated by Django 5.1.4 on 2024-12-27 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0003_alter_coment_film'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'default_related_name': 'categories', 'ordering': ('name',), 'verbose_name': 'категория', 'verbose_name_plural': 'Категории'},
        ),
    ]
