# Generated by Django 5.1.4 on 2025-01-19 20:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0004_remove_filmsdmodel_torrent_torrent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='torrent',
            name='film',
        ),
        migrations.RemoveField(
            model_name='filmsdmodel',
            name='torrent',
        ),
        migrations.AddField(
            model_name='filmsdmodel',
            name='torrent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='films.torrent', verbose_name='Торрент'),
        ),
    ]
