# Generated by Django 5.1.4 on 2025-01-19 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0005_remove_torrent_film_remove_filmsdmodel_torrent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmsdmodel',
            name='torrent',
        ),
        migrations.AddField(
            model_name='torrent',
            name='film',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='torrents', to='films.filmsdmodel', verbose_name='Фильм'),
            preserve_default=False,
        ),
    ]
