# Generated by Django 5.1.4 on 2025-01-01 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0002_initial'),
        ('news', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventuser',
            options={'ordering': ('created_at',), 'verbose_name': 'событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='eventuser',
            name='film',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='film_events', to='films.filmsdmodel', verbose_name='Фильм'),
        ),
        migrations.AddField(
            model_name='eventuser',
            name='related_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_user_events', to=settings.AUTH_USER_MODEL, verbose_name='Связанный пользователь'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='event',
            field=models.CharField(choices=[('add_film', 'добавил фильм в избранное'), ('del_film', 'удалил фильм в избранное'), ('follow_user', 'подписался на пользователя'), ('unfollow_user', 'отписался от пользователя')], max_length=256, verbose_name='Событие'),
        ),
    ]
