# Generated by Django 5.1.4 on 2025-01-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventuser',
            name='event',
            field=models.CharField(choices=[('add_film', 'добавил фильм в избранное'), ('del_film', 'удалил фильм из избранного'), ('follow_user', 'подписался на пользователя'), ('unfollow_user', 'отписался от пользователя'), ('add_comment', 'оставил отзыв на фильм'), ('del_comment', 'удалил свой отзыв на фильм')], max_length=256, verbose_name='Событие'),
        ),
    ]
