# Generated by Django 5.1.4 on 2025-01-06 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_message_unique_name_receiver'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='unique_name_receiver',
        ),
    ]
