name: Основной рабочий процесс KinoZ
on:
  push:
    branches:
      - main
jobs:
  backend_tests:
    name: Тестирование backend
    runs-on: ubuntu-latest
    steps:
      - name: Получения исходного кода
        uses: actions/checkout@v3
      - name: Установка пайтон
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Установка зависимостей
        run: |
          python -m pip install --upgrade pip 
          pip install flake8==6.0.0
          pip install -r ./backend/requirements.txt 
      - name: Проверяем flake8
        run: python -m flake8 backend/
